excluded:
  - Tests/TestFiles
  - Sources/DeduperCore/Resources
  - Sources/DeduperApp/Resources

# Rules configuration
line_length:
  warning: 120
  error: 150
  ignores_function_declarations: true
  ignores_comments: true
  ignores_interpolated_strings: true

function_body_length:
  warning: 50
  error: 100

type_body_length:
  warning: 200
  error: 300

file_length:
  warning: 400
  error: 600

cyclomatic_complexity:
  warning: 10
  error: 15

# Disable rules that conflict with project style
disabled_rules:
  - trailing_comma
  - identifier_name
  - type_name

# Custom rules
custom_rules:
  # Prefer const over let for immutable declarations
  prefer_const_over_let:
    included: ".*\\.swift"
    name: "Prefer const over let"
    regex: "\\blet\\s+\\w+\\s*[:=]\\s*\\w+"
    message: "Use 'const' instead of 'let' for immutable declarations"
    severity: warning

  # No emojis in comments or documentation
  no_emojis_in_comments:
    included: ".*\\.swift"
    name: "No Emojis in Comments"
    regex: "[\\u{1F600}-\\u{1F64F}|\\u{1F300}-\\u{1F5FF}|\\u{1F680}-\\u{1F6FF}|\\u{1F1E0}-\\u{1F1FF}|\\u{2600}-\\u{26FF}|\\u{2700}-\\u{27BF}]"
    message: "Emojis are not allowed in code comments or documentation"
    severity: error

opt_in_rules:
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_first_not_nil
  - convenience_type
  - discouraged_assert
  - discouraged_none_name
  - discouraged_object_literal
  - discouraged_optional_boolean
  - discouraged_optional_collection
  - empty_collection_literal
  - empty_count
  - empty_string
  - explicit_init
  - extension_access_modifier
  - file_header
  - file_name
  - first_where
  - flatmap_over_map_reduce
  - identical_operands
  - implicit_return
  - joined_default_parameter
  - last_where
  - legacy_constant
  - legacy_constructor
  - legacy_nsgeometry_functions
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - modifier_order
  - multiline_arguments
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - no_extension_access_modifier
  - object_literal
  - operator_usage_whitespace
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  - prefer_self_in_static_references
  - prefer_self_type_over_type_of_self
  - prefer_zero_over_explicit_init
  - private_action
  - private_outlet
  - prohibited_super_call
  - redundant_nil_coalescing
  - redundant_type_annotation
  - required_enum_case
  - single_test_class
  - sorted_first_last
  - static_operator
  - unneeded_break_in_switch
  - unowned_variable_capture
  - untyped_error_in_catch
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - xctest_case_description
  - yoda_condition
