openapi: 3.0.3
info:
  title: 'Merge & Replace Operations API'
  version: '1.0.0'
  description: 'API contracts for merge and replace operations in the Deduper application'

servers:
  - url: '/api/v1'
    description: 'Merge Operations API'

paths:
  /merge/suggest-keeper:
    post:
      summary: 'Suggest the best keeper for a duplicate group'
      operationId: 'suggestKeeper'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: 'object'
              required: ['groupId']
              properties:
                groupId:
                  type: 'string'
                  description: 'ID of the duplicate group'
      responses:
        '200':
          description: 'Suggested keeper information'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/KeeperSuggestion'
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'

  /merge:
    post:
      summary: 'Execute merge operation on a duplicate group'
      operationId: 'mergeGroup'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: 'object'
              required: ['groupId', 'keeperId']
              properties:
                groupId:
                  type: 'string'
                  description: 'ID of the duplicate group to merge'
                keeperId:
                  type: 'string'
                  description: 'ID of the file to keep'
                dryRun:
                  type: 'boolean'
                  default: false
                  description: 'If true, only preview the merge without executing'
      responses:
        '200':
          description: 'Merge operation result'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MergeResult'
        '400':
          $ref: '#/components/responses/BadRequest'
        '409':
          $ref: '#/components/responses/Conflict'
        '500':
          $ref: '#/components/responses/InternalServerError'

  /merge/undo:
    post:
      summary: 'Undo the last merge operation'
      operationId: 'undoLastMerge'
      responses:
        '200':
          description: 'Undo operation result'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UndoResult'
        '400':
          $ref: '#/components/responses/BadRequest'
        '500':
          $ref: '#/components/responses/InternalServerError'

  /merge/transaction/{transactionId}:
    get:
      summary: 'Get details of a specific transaction'
      operationId: 'getTransaction'
      parameters:
        - name: 'transactionId'
          in: 'path'
          required: true
          schema:
            type: 'string'
      responses:
        '200':
          description: 'Transaction details'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransactionDetail'
        '404':
          $ref: '#/components/responses/NotFound'

  /merge/transactions:
    get:
      summary: 'List recent transactions'
      operationId: 'listTransactions'
      parameters:
        - name: 'limit'
          in: 'query'
          schema:
            type: 'integer'
            minimum: 1
            maximum: 100
            default: 20
        - name: 'offset'
          in: 'query'
          schema:
            type: 'integer'
            minimum: 0
            default: 0
      responses:
        '200':
          description: 'List of recent transactions'
          content:
            application/json:
              schema:
                type: 'object'
                required: ['transactions', 'total']
                properties:
                  transactions:
                    type: 'array'
                    items:
                      $ref: '#/components/schemas/TransactionSummary'
                  total:
                    type: 'integer'

components:
  schemas:
    KeeperSuggestion:
      type: 'object'
      required: ['keeperId', 'reason', 'confidence', 'alternatives']
      properties:
        keeperId:
          type: 'string'
          description: 'ID of the suggested keeper file'
        reason:
          type: 'string'
          enum: ['resolution', 'file_size', 'format_preference', 'metadata_completeness']
          description: 'Primary reason for this suggestion'
        confidence:
          type: 'number'
          minimum: 0
          maximum: 1
          description: 'Confidence score for this suggestion'
        alternatives:
          type: 'array'
          items:
            type: 'object'
            properties:
              fileId:
                type: 'string'
              reason:
                type: 'string'
              confidence:
                type: 'number'

    MergeResult:
      type: 'object'
      required: ['success', 'transactionId', 'keeperId', 'operations']
      properties:
        success:
          type: 'boolean'
          description: 'Whether the merge operation succeeded'
        transactionId:
          type: 'string'
          description: 'Unique identifier for this transaction'
        keeperId:
          type: 'string'
          description: 'ID of the file that was kept'
        operations:
          type: 'array'
          items:
            $ref: '#/components/schemas/MergeOperation'
        dryRun:
          type: 'boolean'
          description: 'Whether this was a dry run'
        preview:
          $ref: '#/components/schemas/MergePreview'

    MergeOperation:
      type: 'object'
      required: ['type', 'fileId', 'status']
      properties:
        type:
          type: 'string'
          enum: ['exif_write', 'file_move', 'trash_move', 'metadata_merge']
        fileId:
          type: 'string'
          description: 'ID of the affected file'
        status:
          type: 'string'
          enum: ['success', 'failed', 'skipped']
        details:
          type: 'object'
          additionalProperties: true

    MergePreview:
      type: 'object'
      required: ['keeper', 'toRemove', 'exifChanges', 'spaceSaved']
      properties:
        keeper:
          $ref: '#/components/schemas/FileInfo'
        toRemove:
          type: 'array'
          items:
            $ref: '#/components/schemas/FileInfo'
        exifChanges:
          type: 'array'
          items:
            type: 'object'
            properties:
              field:
                type: 'string'
              oldValue:
                type: 'string'
              newValue:
                type: 'string'
              sourceFile:
                type: 'string'
        spaceSaved:
          type: 'integer'
          description: 'Bytes that will be saved by this merge'

    UndoResult:
      type: 'object'
      required: ['success', 'transactionId', 'restoredFiles']
      properties:
        success:
          type: 'boolean'
          description: 'Whether the undo operation succeeded'
        transactionId:
          type: 'string'
          description: 'ID of the transaction that was undone'
        restoredFiles:
          type: 'array'
          items:
            type: 'string'
          description: 'IDs of files that were restored'
        metadataReverted:
          type: 'array'
          items:
            type: 'string'
          description: 'Fields that had metadata reverted'

    TransactionDetail:
      type: 'object'
      required: ['id', 'timestamp', 'status', 'operations']
      properties:
        id:
          type: 'string'
        timestamp:
          type: 'string'
          format: 'date-time'
        status:
          type: 'string'
          enum: ['active', 'committed', 'rolled_back', 'undone']
        operations:
          type: 'array'
          items:
            $ref: '#/components/schemas/MergeOperation'
        metadata:
          type: 'object'
          additionalProperties: true

    TransactionSummary:
      type: 'object'
      required: ['id', 'timestamp', 'status', 'fileCount']
      properties:
        id:
          type: 'string'
        timestamp:
          type: 'string'
          format: 'date-time'
        status:
          type: 'string'
          enum: ['active', 'committed', 'rolled_back', 'undone']
        fileCount:
          type: 'integer'
          description: 'Number of files affected by this transaction'
        spaceSaved:
          type: 'integer'
          description: 'Space saved by this transaction'

    FileInfo:
      type: 'object'
      required: ['id', 'name', 'path', 'size']
      properties:
        id:
          type: 'string'
        name:
          type: 'string'
        path:
          type: 'string'
        size:
          type: 'integer'
        metadata:
          type: 'object'
          additionalProperties: true
        thumbnail:
          type: 'string'
          format: 'uri'

  responses:
    BadRequest:
      description: 'Bad request'
      content:
        application/json:
          schema:
            type: 'object'
            required: ['error', 'code']
            properties:
              error:
                type: 'string'
              code:
                type: 'string'
              details:
                type: 'object'

    NotFound:
      description: 'Resource not found'
      content:
        application/json:
          schema:
            type: 'object'
            required: ['error', 'code']
            properties:
              error:
                type: 'string'
              code:
                type: 'string'

    Conflict:
      description: 'Conflict with current state'
      content:
        application/json:
          schema:
            type: 'object'
            required: ['error', 'code']
            properties:
              error:
                type: 'string'
              code:
                type: 'string'

    InternalServerError:
      description: 'Internal server error'
      content:
        application/json:
          schema:
            type: 'object'
            required: ['error', 'code']
            properties:
              error:
                type: 'string'
              code:
                type: 'string'
