openapi: 3.0.3
info:
  title: 'Performance Optimizations API'
  version: '1.0.0'
  description: 'API contracts for performance monitoring and optimization in the Deduper application'

servers:
  - url: '/api/v1'
    description: 'Performance Monitoring API'

paths:
  /performance/metrics:
    post:
      summary: 'Record performance metrics for an operation'
      operationId: 'recordMetrics'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: 'object'
              required: ['operation', 'metrics']
              properties:
                operation:
                  type: 'string'
                  description: 'Name of the operation being monitored'
                metrics:
                  $ref: '#/components/schemas/PerformanceMetrics'
      responses:
        '200':
          description: 'Metrics recorded successfully'
          content:
            application/json:
              schema:
                type: 'object'
                required: ['success', 'metricsId']
                properties:
                  success:
                    type: 'boolean'
                  metricsId:
                    type: 'string'
                    description: 'Unique identifier for the recorded metrics'
        '400':
          $ref: '#/components/responses/BadRequest'
        '500':
          $ref: '#/components/responses/InternalServerError'

  /performance/monitor/start:
    post:
      summary: 'Start monitoring a performance operation'
      operationId: 'startMonitoring'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: 'object'
              required: ['operation', 'operationId']
              properties:
                operation:
                  type: 'string'
                  description: 'Type of operation to monitor'
                operationId:
                  type: 'string'
                  description: 'Unique identifier for this operation instance'
                metadata:
                  type: 'object'
                  additionalProperties: true
                  description: 'Additional context for the operation'
      responses:
        '200':
          description: 'Monitoring started successfully'
          content:
            application/json:
              schema:
                type: 'object'
                required: ['success', 'monitorId']
                properties:
                  success:
                    type: 'boolean'
                  monitorId:
                    type: 'string'
                    description: 'Unique identifier for the monitoring session'
        '400':
          $ref: '#/components/responses/BadRequest'
        '409':
          $ref: '#/components/responses/Conflict'

  /performance/monitor/{monitorId}/stop:
    post:
      summary: 'Stop monitoring an operation and record final metrics'
      operationId: 'stopMonitoring'
      parameters:
        - name: 'monitorId'
          in: 'path'
          required: true
          schema:
            type: 'string'
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: 'object'
              properties:
                itemsProcessed:
                  type: 'integer'
                  description: 'Number of items processed by the operation'
                additionalNotes:
                  type: 'string'
                  description: 'Additional context or notes about the operation'
      responses:
        '200':
          description: 'Monitoring stopped and metrics recorded'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MonitoringResult'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'

  /performance/optimizations:
    get:
      summary: 'Get optimization recommendations based on performance data'
      operationId: 'getOptimizations'
      parameters:
        - name: 'limit'
          in: 'query'
          schema:
            type: 'integer'
            minimum: 1
            maximum: 50
            default: 10
        - name: 'priority'
          in: 'query'
          schema:
            type: 'string'
            enum: ['high', 'medium', 'low']
            default: 'medium'
      responses:
        '200':
          description: 'Optimization recommendations'
          content:
            application/json:
              schema:
                type: 'object'
                required: ['recommendations', 'total']
                properties:
                  recommendations:
                    type: 'array'
                    items:
                      $ref: '#/components/schemas/OptimizationRecommendation'
                  total:
                    type: 'integer'
        '500':
          $ref: '#/components/responses/InternalServerError'

  /performance/optimizations/{recommendationId}/apply:
    post:
      summary: 'Apply a specific optimization recommendation'
      operationId: 'applyOptimization'
      parameters:
        - name: 'recommendationId'
          in: 'path'
          required: true
          schema:
            type: 'string'
      responses:
        '200':
          description: 'Optimization applied successfully'
          content:
            application/json:
              schema:
                type: 'object'
                required: ['success', 'appliedAt']
                properties:
                  success:
                    type: 'boolean'
                  appliedAt:
                    type: 'string'
                    format: 'date-time'
                  expectedImpact:
                    $ref: '#/components/schemas/PerformanceImpact'
        '404':
          $ref: '#/components/responses/NotFound'
        '409':
          $ref: '#/components/responses/Conflict'

  /performance/resource-thresholds:
    get:
      summary: 'Get current resource usage thresholds'
      operationId: 'getResourceThresholds'
      responses:
        '200':
          description: 'Current resource thresholds'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResourceThresholds'
        '500':
          $ref: '#/components/responses/InternalServerError'

    put:
      summary: 'Update resource usage thresholds'
      operationId: 'updateResourceThresholds'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ResourceThresholds'
      responses:
        '200':
          description: 'Thresholds updated successfully'
          content:
            application/json:
              schema:
                type: 'object'
                required: ['success', 'updatedAt']
                properties:
                  success:
                    type: 'boolean'
                  updatedAt:
                    type: 'string'
                    format: 'date-time'
        '400':
          $ref: '#/components/responses/BadRequest'
        '500':
          $ref: '#/components/responses/InternalServerError'

  /performance/system-metrics:
    get:
      summary: 'Get current system performance metrics'
      operationId: 'getSystemMetrics'
      responses:
        '200':
          description: 'Current system metrics'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SystemMetrics'
        '500':
          $ref: '#/components/responses/InternalServerError'

components:
  schemas:
    PerformanceMetrics:
      type: 'object'
      required: ['operation', 'duration', 'memoryUsage', 'cpuUsage', 'timestamp']
      properties:
        operation:
          type: 'string'
          description: 'Name of the operation'
        duration:
          type: 'number'
          format: 'float'
          minimum: 0
          description: 'Operation duration in milliseconds'
        memoryUsage:
          type: 'integer'
          format: 'int64'
          minimum: 0
          description: 'Memory usage in bytes'
        cpuUsage:
          type: 'number'
          format: 'float'
          minimum: 0
          maximum: 100
          description: 'CPU usage percentage'
        itemsProcessed:
          type: 'integer'
          minimum: 0
          description: 'Number of items processed'
        itemsPerSecond:
          type: 'number'
          format: 'float'
          minimum: 0
          description: 'Processing rate'
        timestamp:
          type: 'string'
          format: 'date-time'
          description: 'When the metrics were recorded'
        metadata:
          type: 'object'
          additionalProperties: true
          description: 'Additional operation-specific data'

    MonitoringResult:
      type: 'object'
      required: ['monitorId', 'operation', 'metrics']
      properties:
        monitorId:
          type: 'string'
          description: 'Unique identifier for the monitoring session'
        operation:
          type: 'string'
          description: 'Type of operation that was monitored'
        metrics:
          $ref: '#/components/schemas/PerformanceMetrics'
        recommendations:
          type: 'array'
          items:
            $ref: '#/components/schemas/OptimizationRecommendation'
          description: 'Optimization recommendations based on the metrics'

    OptimizationRecommendation:
      type: 'object'
      required: ['id', 'type', 'description', 'priority', 'confidence']
      properties:
        id:
          type: 'string'
          description: 'Unique identifier for the recommendation'
        type:
          type: 'string'
          enum: ['concurrency', 'memory', 'algorithm', 'caching', 'resource_management']
          description: 'Category of optimization'
        description:
          type: 'string'
          description: 'Human-readable description of the recommendation'
        priority:
          type: 'string'
          enum: ['high', 'medium', 'low']
          description: 'Priority level for applying this recommendation'
        confidence:
          type: 'number'
          format: 'float'
          minimum: 0
          maximum: 1
          description: 'Confidence score for this recommendation'
        expectedImpact:
          $ref: '#/components/schemas/PerformanceImpact'
        implementationEffort:
          type: 'string'
          enum: ['low', 'medium', 'high']
          description: 'Estimated effort to implement'

    PerformanceImpact:
      type: 'object'
      properties:
        performanceImprovement:
          type: 'number'
          format: 'float'
          minimum: 0
          maximum: 100
          description: 'Expected performance improvement percentage'
        resourceReduction:
          type: 'number'
          format: 'float'
          minimum: 0
          maximum: 100
          description: 'Expected resource usage reduction percentage'
        confidence:
          type: 'number'
          format: 'float'
          minimum: 0
          maximum: 1
          description: 'Confidence in the impact estimate'

    ResourceThresholds:
      type: 'object'
      properties:
        cpuThreshold:
          type: 'number'
          format: 'float'
          minimum: 0
          maximum: 100
          description: 'CPU usage threshold percentage'
        memoryThreshold:
          type: 'integer'
          format: 'int64'
          minimum: 0
          description: 'Memory usage threshold in bytes'
        diskIOThreshold:
          type: 'integer'
          format: 'int64'
          minimum: 0
          description: 'Disk I/O threshold in bytes per second'
        concurrencyLimit:
          type: 'integer'
          minimum: 1
          description: 'Maximum concurrent operations limit'
        updatedAt:
          type: 'string'
          format: 'date-time'
          description: 'When thresholds were last updated'

    SystemMetrics:
      type: 'object'
      required: ['timestamp', 'cpuUsage', 'memoryUsage', 'diskUsage']
      properties:
        timestamp:
          type: 'string'
          format: 'date-time'
          description: 'When the metrics were collected'
        cpuUsage:
          type: 'number'
          format: 'float'
          minimum: 0
          maximum: 100
          description: 'Current CPU usage percentage'
        memoryUsage:
          type: 'integer'
          format: 'int64'
          minimum: 0
          description: 'Current memory usage in bytes'
        diskUsage:
          type: 'integer'
          format: 'int64'
          minimum: 0
          description: 'Current disk usage in bytes'
        networkUsage:
          type: 'integer'
          format: 'int64'
          minimum: 0
          description: 'Current network usage in bytes per second'
        activeOperations:
          type: 'integer'
          minimum: 0
          description: 'Number of currently active operations'
        queuedOperations:
          type: 'integer'
          minimum: 0
          description: 'Number of queued operations'

  responses:
    BadRequest:
      description: 'Bad request'
      content:
        application/json:
          schema:
            type: 'object'
            required: ['error', 'code']
            properties:
              error:
                type: 'string'
              code:
                type: 'string'
              details:
                type: 'object'

    NotFound:
      description: 'Resource not found'
      content:
        application/json:
          schema:
            type: 'object'
            required: ['error', 'code']
            properties:
              error:
                type: 'string'
              code:
                type: 'string'

    Conflict:
      description: 'Conflict with current state'
      content:
        application/json:
          schema:
            type: 'object'
            required: ['error', 'code']
            properties:
              error:
                type: 'string'
              code:
                type: 'string'

    InternalServerError:
      description: 'Internal server error'
      content:
        application/json:
          schema:
            type: 'object'
            required: ['error', 'code']
            properties:
              error:
                type: 'string'
              code:
                type: 'string'
