openapi: 3.0.3
info:
  title: Deduper Testing Enhancements API
  version: 1.0.0
  description: API for advanced testing and performance enhancements

paths:
  /chaos/test:
    post:
      summary: Execute chaos testing scenarios
      operationId: executeChaosTest
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ChaosTestRequest'
      responses:
        '200':
          description: Chaos test completed successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChaosTestResponse'
        '400':
          description: Invalid chaos test configuration
        '500':
          description: Chaos test execution failed

  /ab/experiment:
    post:
      summary: Execute A/B testing experiment
      operationId: executeABExperiment
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ABExperimentRequest'
      responses:
        '200':
          description: A/B experiment completed successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ABExperimentResponse'
        '400':
          description: Invalid A/B experiment configuration

  /index/precompute:
    post:
      summary: Build pre-computed index for dataset
      operationId: buildPrecomputedIndex
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/IndexBuildRequest'
      responses:
        '200':
          description: Index built successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IndexBuildResponse'
        '400':
          description: Invalid index build configuration
        '503':
          description: Insufficient resources for index building

  /performance/benchmark:
    post:
      summary: Execute performance benchmark
      operationId: executeBenchmark
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BenchmarkRequest'
      responses:
        '200':
          description: Benchmark completed successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BenchmarkResponse'
        '400':
          description: Invalid benchmark configuration

components:
  schemas:
    ChaosTestRequest:
      type: object
      required:
        - scenarios
        - datasetSize
        - duration
      properties:
        scenarios:
          type: array
          items:
            $ref: '#/components/schemas/ChaosScenario'
        datasetSize:
          type: integer
          minimum: 100
          maximum: 100000
        duration:
          type: integer
          minimum: 1000
          maximum: 300000
          description: Test duration in milliseconds
        configuration:
          $ref: '#/components/schemas/ChaosConfiguration'

    ChaosTestResponse:
      type: object
      properties:
        testId:
          type: string
          format: uuid
        scenariosExecuted:
          type: integer
        totalFailures:
          type: integer
        recoverySuccessRate:
          type: number
          format: float
        performanceDegradation:
          type: number
          format: float
        metrics:
          $ref: '#/components/schemas/ChaosMetrics'
        recommendations:
          type: array
          items:
            type: string

    ChaosScenario:
      type: object
      required:
        - type
        - severity
      properties:
        type:
          type: string
          enum: [network_failure, disk_space, memory_pressure, permission_error]
        severity:
          type: string
          enum: [low, medium, high]
        parameters:
          type: object
          additionalProperties: true

    ChaosConfiguration:
      type: object
      properties:
        failFast:
          type: boolean
          default: false
        maxFailures:
          type: integer
          default: 100
        recoveryTimeout:
          type: integer
          default: 5000

    ChaosMetrics:
      type: object
      properties:
        networkFailuresInjected:
          type: integer
        diskSpaceExhausted:
          type: integer
        memoryPressureEvents:
          type: integer
        permissionErrors:
          type: integer
        operationsCompleted:
          type: integer
        operationsFailed:
          type: integer

    ABExperimentRequest:
      type: object
      required:
        - name
        - variants
        - dataset
        - metrics
      properties:
        name:
          type: string
        description:
          type: string
        variants:
          type: array
          items:
            $ref: '#/components/schemas/ExperimentVariant'
        dataset:
          $ref: '#/components/schemas/ExperimentDataset'
        metrics:
          type: array
          items:
            $ref: '#/components/schemas/MetricDefinition'
        sampleSize:
          type: integer
          minimum: 100
          default: 1000
        confidenceLevel:
          type: number
          format: float
          minimum: 0.8
          maximum: 0.99
          default: 0.95

    ABExperimentResponse:
      type: object
      properties:
        experimentId:
          type: string
          format: uuid
        variantsTested:
          type: integer
        samplesProcessed:
          type: integer
        statisticalSignificance:
          type: number
          format: float
        winner:
          type: string
        confidenceInterval:
          type: number
          format: float
        results:
          type: array
          items:
            $ref: '#/components/schemas/VariantResult'
        recommendations:
          type: array
          items:
            type: string

    ExperimentVariant:
      type: object
      required:
        - name
        - configuration
      properties:
        name:
          type: string
        description:
          type: string
        configuration:
          type: object
          additionalProperties: true

    ExperimentDataset:
      type: object
      required:
        - type
        - size
      properties:
        type:
          type: string
          enum: [exact_duplicates, similar_images, mixed_content, edge_cases]
        size:
          type: integer
          minimum: 100
          maximum: 100000
        parameters:
          type: object
          additionalProperties: true

    MetricDefinition:
      type: object
      required:
        - name
        - type
      properties:
        name:
          type: string
        type:
          type: string
          enum: [accuracy, precision, recall, f1_score, performance, memory_usage]
        threshold:
          type: number
          format: float

    VariantResult:
      type: object
      properties:
        variantName:
          type: string
        mean:
          type: number
          format: float
        standardDeviation:
          type: number
          format: float
        confidenceInterval:
          type: number
          format: float
        statisticalSignificance:
          type: number
          format: float

    IndexBuildRequest:
      type: object
      required:
        - datasetSize
        - indexType
      properties:
        datasetSize:
          type: integer
          minimum: 1000
          maximum: 1000000
        indexType:
          type: string
          enum: [bk_tree, hash_index, lsh, faiss]
        parameters:
          type: object
          additionalProperties: true
        optimizationLevel:
          type: string
          enum: [memory, speed, balanced]
          default: balanced

    IndexBuildResponse:
      type: object
      properties:
        indexId:
          type: string
          format: uuid
        buildTimeMs:
          type: integer
        indexSizeBytes:
          type: integer
        candidateCount:
          type: integer
        collisionRate:
          type: number
          format: float
        memoryUsageMB:
          type: number
          format: float
        performanceMetrics:
          $ref: '#/components/schemas/IndexPerformanceMetrics'

    IndexPerformanceMetrics:
      type: object
      properties:
        averageQueryTime:
          type: number
          format: float
        hitRate:
          type: number
          format: float
        missRate:
          type: number
          format: float
        cacheEfficiency:
          type: number
          format: float

    BenchmarkRequest:
      type: object
      required:
        - name
        - configurations
        - iterations
      properties:
        name:
          type: string
        description:
          type: string
        configurations:
          type: array
          items:
            type: object
            additionalProperties: true
        iterations:
          type: integer
          minimum: 1
          maximum: 100
          default: 10
        warmupIterations:
          type: integer
          minimum: 0
          maximum: 10
          default: 3

    BenchmarkResponse:
      type: object
      properties:
        benchmarkId:
          type: string
          format: uuid
        configurationsTested:
          type: integer
        totalIterations:
          type: integer
        results:
          type: array
          items:
            $ref: '#/components/schemas/BenchmarkResult'
        summary:
          $ref: '#/components/schemas/BenchmarkSummary'

    BenchmarkResult:
      type: object
      properties:
        configurationName:
          type: string
        iterations:
          type: integer
        meanTime:
          type: number
          format: float
        medianTime:
          type: number
          format: float
        standardDeviation:
          type: number
          format: float
        minTime:
          type: number
          format: float
        maxTime:
          type: number
          format: float

    BenchmarkSummary:
      type: object
      properties:
        bestConfiguration:
          type: string
        improvementPercentage:
          type: number
          format: float
        statisticalSignificance:
          type: number
          format: float
        recommendations:
          type: array
          items:
            type: string
