openapi: 3.0.3
info:
  title: 'UI Components API'
  version: '1.0.0'
  description: 'Interface contracts for UI components in the Deduper application'

servers:
  - url: '/api/v1'
    description: 'UI Components API'

paths:
  /groups:
    get:
      summary: 'Get duplicate groups for display'
      operationId: 'getDuplicateGroups'
      parameters:
        - name: 'limit'
          in: 'query'
          schema:
            type: 'integer'
            minimum: 1
            maximum: 100
            default: 50
        - name: 'offset'
          in: 'query'
          schema:
            type: 'integer'
            minimum: 0
            default: 0
        - name: 'sort'
          in: 'query'
          schema:
            type: 'string'
            enum: ['confidence', 'size', 'count', 'name']
            default: 'confidence'
        - name: 'filter'
          in: 'query'
          schema:
            type: 'string'
            enum: ['all', 'high_confidence', 'low_confidence', 'large_groups']
      responses:
        '200':
          description: 'List of duplicate groups'
          content:
            application/json:
              schema:
                type: 'object'
                required: ['groups', 'total', 'hasMore']
                properties:
                  groups:
                    type: 'array'
                    items:
                      $ref: '#/components/schemas/DuplicateGroup'
                  total:
                    type: 'integer'
                  hasMore:
                    type: 'boolean'
        '400':
          $ref: '#/components/responses/BadRequest'
        '500':
          $ref: '#/components/responses/InternalServerError'

  /groups/{groupId}:
    get:
      summary: 'Get detailed information for a specific duplicate group'
      operationId: 'getDuplicateGroup'
      parameters:
        - name: 'groupId'
          in: 'path'
          required: true
          schema:
            type: 'string'
      responses:
        '200':
          description: 'Detailed duplicate group information'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DuplicateGroupDetail'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'

  /groups/{groupId}/merge:
    post:
      summary: 'Execute merge operation for a duplicate group'
      operationId: 'mergeDuplicateGroup'
      parameters:
        - name: 'groupId'
          in: 'path'
          required: true
          schema:
            type: 'string'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: 'object'
              required: ['keeperId', 'mergePlan']
              properties:
                keeperId:
                  type: 'string'
                  description: 'ID of the item to keep'
                mergePlan:
                  $ref: '#/components/schemas/MergePlan'
                dryRun:
                  type: 'boolean'
                  default: false
      responses:
        '200':
          description: 'Merge operation result'
          content:
            application/json:
              schema:
                type: 'object'
                required: ['success', 'operationId', 'itemsAffected']
                properties:
                  success:
                    type: 'boolean'
                  operationId:
                    type: 'string'
                  itemsAffected:
                    type: 'integer'
                  dryRun:
                    type: 'boolean'
                  preview:
                    $ref: '#/components/schemas/MergePreview'
        '400':
          $ref: '#/components/responses/BadRequest'
        '409':
          $ref: '#/components/responses/Conflict'
        '500':
          $ref: '#/components/responses/InternalServerError'

  /evidence/{groupId}:
    get:
      summary: 'Get evidence data for a duplicate group'
      operationId: 'getEvidence'
      parameters:
        - name: 'groupId'
          in: 'path'
          required: true
          schema:
            type: 'string'
      responses:
        '200':
          description: 'Evidence data for the group'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EvidenceData'
        '404':
          $ref: '#/components/responses/NotFound'

  /history:
    get:
      summary: 'Get operation history'
      operationId: 'getHistory'
      parameters:
        - name: 'limit'
          in: 'query'
          schema:
            type: 'integer'
            minimum: 1
            maximum: 100
            default: 20
        - name: 'offset'
          in: 'query'
          schema:
            type: 'integer'
            minimum: 0
            default: 0
      responses:
        '200':
          description: 'Operation history'
          content:
            application/json:
              schema:
                type: 'object'
                required: ['operations', 'total']
                properties:
                  operations:
                    type: 'array'
                    items:
                      $ref: '#/components/schemas/OperationHistory'
                  total:
                    type: 'integer'

components:
  schemas:
    DuplicateGroup:
      type: 'object'
      required: ['id', 'members', 'confidence', 'signals', 'spacePotentialSaved']
      properties:
        id:
          type: 'string'
          description: 'Unique identifier for the duplicate group'
        members:
          type: 'array'
          items:
            $ref: '#/components/schemas/GroupMember'
          minItems: 2
        confidence:
          type: 'number'
          minimum: 0
          maximum: 1
          description: 'Confidence score for this being a true duplicate group'
        signals:
          type: 'array'
          items:
            $ref: '#/components/schemas/Signal'
        spacePotentialSaved:
          type: 'integer'
          description: 'Bytes that could be saved by merging this group'
        createdAt:
          type: 'string'
          format: 'date-time'

    GroupMember:
      type: 'object'
      required: ['id', 'name', 'path', 'size', 'metadata']
      properties:
        id:
          type: 'string'
        name:
          type: 'string'
        path:
          type: 'string'
        size:
          type: 'integer'
        metadata:
          type: 'object'
          additionalProperties: true
        thumbnail:
          type: 'string'
          format: 'uri'
          description: 'URI to thumbnail image'

    Signal:
      type: 'object'
      required: ['type', 'name', 'value', 'confidence']
      properties:
        type:
          type: 'string'
          enum: ['hash', 'name', 'path', 'content', 'metadata']
        name:
          type: 'string'
        value:
          type: 'number'
        confidence:
          type: 'number'
          minimum: 0
          maximum: 1

    DuplicateGroupDetail:
      type: 'object'
      required: ['group', 'evidence', 'canMerge']
      properties:
        group:
          $ref: '#/components/schemas/DuplicateGroup'
        evidence:
          $ref: '#/components/schemas/EvidenceData'
        canMerge:
          type: 'boolean'
        suggestedKeeper:
          type: 'string'
          description: 'ID of suggested item to keep'

    EvidenceData:
      type: 'object'
      required: ['signals', 'thresholds', 'distances', 'overallConfidence']
      properties:
        signals:
          type: 'array'
          items:
            $ref: '#/components/schemas/SignalDetail'
        thresholds:
          type: 'object'
          additionalProperties:
            type: 'number'
        distances:
          type: 'object'
          additionalProperties:
            type: 'number'
        overallConfidence:
          type: 'number'
          minimum: 0
          maximum: 1

    SignalDetail:
      type: 'object'
      required: ['signal', 'threshold', 'distance', 'passed']
      properties:
        signal:
          $ref: '#/components/schemas/Signal'
        threshold:
          type: 'number'
        distance:
          type: 'number'
        passed:
          type: 'boolean'

    MergePlan:
      type: 'object'
      required: ['keeperId', 'removeIds', 'metadataMerges']
      properties:
        keeperId:
          type: 'string'
        removeIds:
          type: 'array'
          items:
            type: 'string'
        metadataMerges:
          type: 'object'
          additionalProperties:
            type: 'string'
            enum: ['keep', 'merge', 'custom']
        customValues:
          type: 'object'
          additionalProperties: true

    MergePreview:
      type: 'object'
      required: ['keeper', 'toRemove', 'spaceSaved', 'metadataChanges']
      properties:
        keeper:
          $ref: '#/components/schemas/GroupMember'
        toRemove:
          type: 'array'
          items:
            $ref: '#/components/schemas/GroupMember'
        spaceSaved:
          type: 'integer'
        metadataChanges:
          type: 'array'
          items:
            type: 'object'
            properties:
              field:
                type: 'string'
              oldValue:
                type: 'string'
              newValue:
                type: 'string'

    OperationHistory:
      type: 'object'
      required: ['id', 'type', 'timestamp', 'description', 'canUndo']
      properties:
        id:
          type: 'string'
        type:
          type: 'string'
          enum: ['merge', 'restore', 'delete']
        timestamp:
          type: 'string'
          format: 'date-time'
        description:
          type: 'string'
        canUndo:
          type: 'boolean'
        groupId:
          type: 'string'
        itemsAffected:
          type: 'integer'

  responses:
    BadRequest:
      description: 'Bad request'
      content:
        application/json:
          schema:
            type: 'object'
            required: ['error', 'code']
            properties:
              error:
                type: 'string'
              code:
                type: 'string'
              details:
                type: 'object'

    NotFound:
      description: 'Resource not found'
      content:
        application/json:
          schema:
            type: 'object'
            required: ['error', 'code']
            properties:
              error:
                type: 'string'
              code:
                type: 'string'

    Conflict:
      description: 'Conflict with current state'
      content:
        application/json:
          schema:
            type: 'object'
            required: ['error', 'code']
            properties:
              error:
                type: 'string'
              code:
                type: 'string'

    InternalServerError:
      description: 'Internal server error'
      content:
        application/json:
          schema:
            type: 'object'
            required: ['error', 'code']
            properties:
              error:
                type: 'string'
              code:
                type: 'string'
